name: Run Unit Tests, Lint Files and Build Project
on: push
jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node 24
        uses: actions/setup-node@v4
        with:
          node-version: "24"
      - name: Install dependencies
        run: npm install
      - name: Run lint
        run: npm run lint
      - name: Run tests and coverage
        run: npm run coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Build application
        run: npm run build
